### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by VishnuVNairCodes**
Added modal component.
Also:
1) changed article tag to main tag in all html files
2) added links to all future components in sidebar

Deploy preview: https://deploy-preview-15--minnal-ui.netlify.app/

### CODE REVIEW

**Review by AswathyVNair — APPROVED** [review]

**Review by purohitdheeraj — APPROVED** [review]
Good to merge
rem units can be used as px
instead of 0.5rem just use 5px

**Comment by purohitdheeraj** [comment]
after navigating to the docs page I can see an empty get started page
so are you going to add something to that?

**Comment by VishnuVNairCodes** [comment]
> Good to merge rem units can be used as px instead of 0.5rem just use 5px

Thank you. Will keep that in mind.

**Comment by VishnuVNairCodes** [comment]
> after navigating to the docs page I can see an empty get started page so are you going to add something to that?

The documentation website is still not done yet. I added it at the start, I may remove it afterwards.

**Comment by purohitdheeraj** [comment]
hey I forgot to mention less for less than 1rem units like 0.7rem, 0.8rem, 0.4 use px
otherwise, rem is a good convention to use 👍

**Comment by VishnuVNairCodes** [comment]
> hey I forgot to mention less for less than 1rem units like 0.7rem, 0.8rem, 0.4 use px otherwise, rem is a good convention to use 👍

Yes, got the point. Thank you Dheeraj

**Pull request merged**
